version: "3.7"

services:
  EthanPetStore:
    image: ethanpetstore:lasted
    container_name: EthanPetStore
    ports:
      - 3000:8081
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: ethanpetstore
  mysql:
    image: mysql:5.5.56
    volumes:
      - ethan-mysql-data:/var/lib/mysql
      - ./data:/mnt
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ethanpetstore
      command: sh -c "mysql -p123456;create database ethanpetstore;use ethanpetstore;source /mnt/ethanpetstore.sql"
volumes:
  ethan-mysql-data: